/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Sammys.Snackies;

public class App {

    public static void main(String[] args) {

        VendingMachine vm = new VendingMachine();

        vm.readFromFile("testRead.json");
        System.out.println(vm.toString());
    }
}
